DDT-764: Refactor EBL to use event-core
dcsaorg/DCSA-EBL pull request #128
Opened 2022-01-21 10:40 UTC by mp-assco

2022-01-21 12:48 UTC, pimg requested changes

2022-01-21 12:48 UTC, pimg commented on src/main/java/org/dcsa/ebl/service/impl/BookingServiceImpl.java
> +//package org.dcsa.ebl.service.impl;
either remove it or if it shouldn't be removed the BookingRepository needs to be changed so it extends the ExtendedRepository

2022-01-21 12:48 UTC, pimg commented on .github/workflows/microservices.yml
> +#    - name: Run API validator
shouldn't this be removed

2022-01-21 12:48 UTC, pimg commented on src/main/java/org/dcsa/ebl/service/impl/EquipmentServiceImpl.java
> +        return Mono.empty();
shouldn't this be removed

2022-01-21 12:51 UTC, douradofrazer requested changes

2022-01-21 12:51 UTC, douradofrazer commented on src/main/resources/application.yaml
>  auth0:
This can be removed, refer to DCSA-BKG `application.yaml`

2022-01-21 13:14 UTC, pimg approved these changes

2022-01-24 14:27 UTC, pimg approved these changes

2022-01-24 15:43 UTC, merged