Ddt 874 integration tests si summaries
dcsaorg/DCSA-EBL pull request #163
Opened 2022-03-07 09:34 UTC by FinnAtAsseco

2022-03-07 09:38 UTC, nt-as commented on src/test/java/ebl/v2/ShippingInstructionSummariesIT.java
> +    assertTrue(response.body().jsonPath().getList("$").size() >= 5);
I think the `assertTrue` line can be replaced with this chain

```
      .body("size()", greaterThanOrEqualTo(5))
```

2022-03-07 09:38 UTC, nt-as commented on src/test/java/ebl/v2/ShippingInstructionSummariesIT.java
> +    assertTrue(response.body().jsonPath().getList("$").size() < allCount);
I think the assertTrue lines can be replaced with this chain

```
      .body("size()", greaterThanOrEqualTo(3))
      .body("size()", lessThan(3))
```

2022-03-16 10:35 UTC, douradofrazer requested changes

2022-03-16 10:35 UTC, douradofrazer commented on src/main/java/org/dcsa/ebl/controller/ShippingInstructionSummariesController.java
> +    log.debug("findShippingInstructionSummaries: carrierBookingReference='{}', documentStatus='{}'", carrierBookingReference, documentStatus);
The log can be removed.

2022-03-23 09:26 UTC, douradofrazer approved these changes

2022-03-23 09:35 UTC, merged